name: Build and push Windows Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Docker image version
        required: true

jobs:
  docker:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u brianveldman -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build image
        run: |
          docker build `
            --file docker/Dockerfile `
            --tag brianveldman/zerotrustassessment:${{ github.event.inputs.version }} `
            docker

      - name: Push image
        run: |
          docker push brianveldman/zerotrustassessment:${{ github.event.inputs.version }}
